name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # Roda uma vez ao dia
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: vn38359/github-profile-summary-cards@v0.8.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME: tokyonight
